In [2]:
import numpy as np

In [4]:
matriz_intrinseca = np.array([[3.0214060e+02,   0.0000000e+00,   0.0000000e+00],
                              [0.0000000e+00,   3.0202364e+02 ,  0.0000000e+00],
                              [1.5870089e+02,   1.1872175e+02,   1.0000000e+00]])

In [5]:
def homogeneo_para_cartesiano(vetor_coord_homogenea):
    vetor = vetor_coord_homogenea[:-1,:] / vetor_coord_homogenea[-1,0]
    return vetor

In [6]:
def cartesiano_para_homogeneo(vetor):
    vetor_coord_homogenea = np.append(vetor, np.array([[1]]), 0)
    return vetor_coord_homogenea

In [9]:
def transformacao_projetiva_3d(ponto_projetado_2d_homogeneo, matriz_intrinseca):
    ponto3d = np.linalg.inv(matriz_intrinseca) @ ponto_projetado_2d_homogeneo
    return ponto3d

In [11]:
cross_points = np.array([[[1, 2]], [[3, 4]], [[5, 6]], [[7, 8]]]) #exemplo
cross_points3d = []
for point2d in cross_points:
  point_homogeneo = cartesiano_para_homogeneo(point2d.T)
  point3d = transformacao_projetiva_3d(point_homogeneo, matriz_intrinseca)
  cross_points3d.append(point3d)

cross_points3d = np.array(cross_points3d)

[[[ 3.30971740e-03]
  [ 6.62199820e-03]
  [-3.11430311e-01]]

 [[ 9.92915219e-03]
  [ 1.32439964e-02]
  [-2.14811572e+00]]

 [[ 1.65485870e-02]
  [ 1.98659946e-02]
  [-3.98480113e+00]]

 [[ 2.31680218e-02]
  [ 2.64879928e-02]
  [-5.82148653e+00]]]


In [13]:
distances = np.array([np.linalg.norm(point3d) for point3d in cross_points3d])

[0.31151829 2.14817949 3.98488501 5.82159289]


Por convenção, escolhe-se a primeira distância

In [14]:
print(distances[0])

0.3115182880016871
